apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: kafka-cluster
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: local-cluster
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: kafka-cluster
    repoURL: https://github.com/MichalIzdebski/local-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true